<a href="https://colab.research.google.com/github/JvNeo/Estudo_Pandas/blob/main/Desafios_e_saber_mais_(Pandas_transforma%C3%A7%C3%A3o_e_manipula%C3%A7%C3%A3o_de_dados).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

01.Para saber mais: precificação inteligente
---

A precificação inteligente para hospedagem é uma estratégia de estimação de preços de forma automatizada e dinâmica, que considera fatores como oferta e demanda, sazonalidade, eventos locais, características do local, entre outros. Com base nessas informações, um algoritmo pode ajustar os preços para maximizar a receita e a rentabilidade da pessoa proprietária.

Normalmente essa estratégia é aplicada a um modelo de inteligência artificial que ajusta automaticamente os preços das diárias. Por exemplo, se a demanda por hospedagem em um determinado destino aumentar, a precificação inteligente ajustará automaticamente os preços das diárias para cima, com o fim de maximizar a receita da propriedade. Da mesma forma, se a demanda diminuir, a precificação inteligente ajustará os preços para baixo para manter a ocupação da propriedade e evitar perdas financeiras.

Embora o machine learning seja frequentemente usado em sistemas de precificação inteligente, existem outras abordagens que podem ser usadas para implementar esses sistemas. Por exemplo, pode-se usar um modelo de regras baseado em lógica e heurísticas para definir as condições e regras de precificação.

Mesmo assim, é importante ressaltar que o uso de machine learning pode oferecer benefícios adicionais, como a capacidade de analisar grandes volumes de dados, identificar padrões de comportamento do consumidor e ajustar os preços de forma mais precisa e dinâmica.

01.Desafio: trabalhando em outros contextos
---

Chegou a hora de pôr em prática tudo o que aprendemos durante as aulas. Preparei dois projetos extras para desenvolvermos durante o curso, para garantir que possamos praticar bastante! Para isso, vamos trabalhar com 2 novos conjuntos de dados, mas que dessa vez serão bem menores. As bases de dados estão disponíveis para download abaixo:

* Projeto desafio 1: vendas online - [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json);
* Projeto desafio 2: administração de condomínios - [dados_locacao_imoveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json).

Em cada aula, desenvolveremos uma etapa dos projetos. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.

*  **Projeto desafio 1: vendas online**

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

A base de dados utilizada nessa análise é a [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json) e contém informações importantes sobre os clientes como, o nome de cadastro do cliente, o valor total pago na compra e o dia da compra.

Sabendo essas informações, o desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o [json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html).



Com essas informações, o desafio do projeto 2: administração de condomínios será similar ao desafio do projeto 1, abrir a base de dados com Pandas e aplicar o [json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html) no DataFrame.

In [41]:
import pandas as pd

In [42]:
dados1 = pd.read_json('/content/drive/MyDrive/ALURA/Pandas: trasnformando e manipulando dados/Arquivos de Desafios/dados_vendas_clientes.json')
dados1

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [43]:
dados1 = pd.json_normalize(dados1['dados_vendas'])
dados1

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

*  **Projeto desafio 2: administração de condomínios**

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece.

Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio de alguns moradores. Disponibilizo a base de dados [dados_locacao_imoveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json), que contém informações sobre o apartamento dos locatários, o dia acordado para o pagamento do aluguel, o dia da efetivação do pagamento de aluguel e o valor do aluguel.

In [44]:
dados2 = pd.read_json('/content/drive/MyDrive/ALURA/Pandas: trasnformando e manipulando dados/Arquivos de Desafios/dados_locacao_imoveis.json')
dados2

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [45]:
dados2 = pd.json_normalize(dados2['dados_locacao'])
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

02.Para saber mais: descrição dos dados
---

Quando trabalhamos com um conjunto de dados qualquer, precisamos saber **quais informações esses dados estão trazendo**, pois só assim conseguiremos estudá-lo e analisá-lo para desenvolver uma solução de análise e tratamento de dados para ele.

Nesse curso, vamos trabalhar com o conjunto de dados presentes no arquivo dados_hospedagem.json e, para que seja possível avançar nos estudos quanto aos dados fornecidos por esse arquivo, vamos entender o que cada coluna traz de informação.

* `avaliacao_geral`: refere-se à média de notas dadas para a avaliação da hospedagem no imóvel.
* `experiencia_local`: descreve as experiências oferecidas durante a hospedagem no imóvel.
* `max_hospedes`: informa a quantidade máxima de hóspedes que o local permite.
* `descricao_local`: descreve o imóvel.
* `descricao_vizinhanca`: descreve a vizinhança ao redor do imóvel.
* `quantidade_banheiros`: informa a quantidade de banheiros disponíveis.
* `quantidade_quartos`: informa a quantidade de quartos disponíveis.
* `quantidade_camas`: informa a quantidade de camas disponíveis.
* `modelo_cama`: informa o modelo de cama oferecido.
* `comodidades`: informa as comodidades oferecidas pelo imóvel.
* `taxa_deposito`: informa a taxa de depósito mínima para segurança de hospedagem.
* `taxa_limpeza`: informa a taxa cobrada para o serviço de limpeza.
* `preco`: refere-se ao preço base a ser cobrado pela diária no imóvel.

02.Para saber mais: precisão de valores numéricos
---

Em geral, quando os dados são muito grandes e temos pouca memória disponível, é comum utilizar tipos de dados mais compactos para reduzir o consumo de memória. Mas, é sempre importante garantir que a **escolha do tipo de dados não prejudique a precisão ou a acurácia dos resultados**.

Quando trabalhamos com números inteiros com Python, podemos ter diversos tipos de dados, cada um com suas limitações e características. Durante as aulas, trabalhamos com o `int64`, um inteiro com precisão de 64 bits. Para entender o significado dessa precisão, é importante conhecer alguns termos técnicos, como byte e bit:

* **Byte**: é uma unidade de medida de informação, que representa um conjunto de 8 bits.
* **Bit**: é a menor unidade de informação utilizada em sistemas digitais, podendo assumir os valores de 0 ou 1.

**Tipo Inteiro**

Com os conceitos de bit e byte claros, podemos, então, entender melhor o significado do `int64`, que é o tipo inteiro que utiliza 8 bytes de armazenamento - 8 bits em cada byte, resultando em 64 bits ao total. Esse tipo inteiro é capaz de representar números muito grandes, que podem variar de `-9.223.372.036.854.775.808` a `9.223.372.036.854.775.807`.

Além dele, temos outros inteiros que podem ter sua precisão definida, como o `int32`, um tipo de dado inteiro que utiliza 4 bytes - 8 bits em cada byte, resultando em 32 bits ao total. Ele é capaz de representar números inteiros menores do que os representados pelo int64, com um máximo de `-2.147.483.648` a `2.147.483.647`.

Pode ser mais comum encontrar os tipos `int64` e `int32`, mas pode ser necessário, em algumas situações, utilizar outros tipos de dados inteiros, como o `int8` ou o `int16`. Tipos de dados como esses são úteis quando é preciso economizar mais memória e não se está trabalhando com grandes valores. Você pode conferir os tipos de inteiros na tabela abaixo:

![Screenshot_3.png]()

A escolha de qual valor de precisão vai depender da situação e da natureza dos dados sendo manipulados. Se os valores que estão sendo analisados são relativamente pequenos, o uso do `int32`, por exemplo, pode ser o suficiente, **podendo economizar espaço em memória**. Entretanto, se tivéssemos trabalhando com dados científicos, por exemplo, que precisam de valores bem grandes, precisaríamos talvez utilizar o `int64`.

**Tipo float**

Além dos inteiros, outros tipos de dados, como o `float`, também utilizam essa opção de precisão como opção de controle de espaço na memória. De maneira semelhante aos números inteiros, o tipo float também apresenta opções de precisão: entre os tipos mais comuns estão o `float32` e o float64.

O tipo `float64` é um número de ponto flutuante com 64 bits de precisão, que representa um número decimal com até 15 dígitos. Por outro lado, o 'float32' é menor tanto em sua capacidade de bits, com 32 ao total, quanto em sua capacidade de precisão de casas decimais, com a capacidade de precisão até 7 dígitos.

02.Desafio: trabalhando em outros contextos
---

Voltemos a pôr em prática tudo o que aprendemos durante as aulas. Disponibilizei novamente os 2 novos conjuntos de dados para download abaixo:

* Projeto desafio 1: vendas online - [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json);
* Projeto desafio 2: administração de condomínios - [dados_locacao_imoveis.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json).

**Lembrando**: São dois projetos de tratamento que serão construídos durante o andamento do curso. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.

**Etapa 2**
* **Projeto desafio 1: vendas online**

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, o novo desafio do projeto 1 será dividido em algumas metas:

* Remover os dados em listas dentro do DataFrame;
* Verificar os tipos de dados;
* Identificar colunas numéricas;
* Transformar a coluna numérica para o tipo numérico.

In [46]:
#visualisando o primeiro df
dados1

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [47]:
# verificando as colunas, criando uma lista delas e atribuindo
colunas1 = list(dados1.columns)
colunas1

['Data de venda', 'Cliente', 'Valor da compra']

In [48]:
# removendo as listas dentro do df com o método explode
dados1 = dados1.explode(colunas1[1:])
dados1

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [49]:
# reset do index para organização
dados1.reset_index(inplace = True, drop=True)
dados1

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [50]:
# verificando os tipos de dados
dados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [51]:
# Coluna 'Valor de compra' é uma coluna numérica

dados1['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [52]:
# Transformando coluna 'Valor de Compra' no tipo numérico
dados1['Valor da compra'] = dados1['Valor da compra'].apply(lambda x: x.replace('R$ ','').replace(',','.').strip())
dados1

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.5
1     06/06/2022  DieGO ARMANDIU 210          573.33
2     06/06/2022  DieGO ARMANDIU 210           392.8
3     06/06/2022  DieGO ARMANDIU 210          512.34
4     07/06/2022  Isabely JOanes 738          825.31
5     07/06/2022  Isabely JOanes 738          168.07
6     07/06/2022  Isabely JOanes 738          339.18
7     07/06/2022  Isabely JOanes 738          314.69
8     08/06/2022  Isabely JOanes 738          682.05
9     08/06/2022    JOãO Gabriel 671          386.34
10    08/06/2022  Julya meireles 914          622.65
11    08/06/2022  Julya meireles 914          630.79
12    09/06/2022  Julya meireles 914           390.3
13    09/06/2022     MaRIA Julia 444          759.16
14    09/06/2022     MaRIA Julia 444          334.47
15    09/06/2022     MaRIA Julia 444          678.78
16    10/06/2022     MaRIA Julia 444          314.24
17    10/06/2022     PEDRO PASCO 812          311.15
18    10/06/2022    Paulo castro 481          899.16
19    10/06/2022   Thiago fritzz 883          885.24

In [53]:
# Inportando biblioteca numpy para trasnformação do tipo
import numpy as np

dados1['Valor da compra'] = dados1['Valor da compra'].astype(np.float64)
dados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

**Projeto desafio 2: administração de condomínios**

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

* Remover os dados em listas dentro do DataFrame;
* Verificar os tipos de dados;
* Identificar colunas numéricas;
* Transformar a coluna numérica para o tipo numérico.

In [54]:
# Visualização do df
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [55]:
# agrupando as colunas em uma lista
colunas2 = list(dados2.columns)
colunas2

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [56]:
# Removendo as listas dentro do df
dados2 = dados2.explode(colunas2[1:])
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [57]:
# resetando o index para melhor compreensão
dados2.reset_index(inplace=True, drop=True)
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [58]:
# verificando os tipos do segundo df
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [59]:
# valor_aluguel é uma coluna numérica
dados2['valor_aluguel'] = dados2['valor_aluguel'].apply(lambda x: x.replace('$ ','').replace(' reais','').replace(',','.'))

In [60]:
# atribuindo o tipo float
dados2['valor_aluguel'] = dados2['valor_aluguel'].astype(np.float64)

In [61]:
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

03.Para saber mais: aprofundando em regex
---

Regex (ou expressão regular) é uma sequência de caracteres que define um padrão de busca em um texto. Ele é uma ferramenta poderosa e versátil que permite encontrar, substituir e manipular padrões de texto de forma eficiente. O regex é amplamente utilizado em diferentes áreas, incluindo programação, ciência de dados e processamento de texto.

Em ciência de dados, o regex é frequentemente usado para processar dados de texto brutos. Algumas dessas aplicações incluem a limpeza de dados, onde o regex pode ser usado para encontrar e substituir certos caracteres. Também pode ser usado em projetos de classificação; um exemplo é usar o regex como auxílio para encontrar padrões no texto de e-mails, o que ajuda a classificar se eles são spam ou não spam.

De maneira geral, o regex permite que os cientistas de dados processem, analisem e classifiquem grandes volumes de dados de texto de forma eficiente e automatizada. O uso adequado do regex pode ajudar a extrair informações valiosas de dados de texto, além de facilitar a limpeza e organização desses dados.

Você pode construir um regex com a ajuda do site [regex101.com](https://regex101.com/). Caso deseje conhecer mais sobre regex e uma aplicação em banco de dados, vale a pena ler o artigo [Principais casos de uso de Regex para tratamento de dados](https://www.alura.com.br/artigos/principais-casos-uso-regex-para-tratamento-dados), que mostra uma aplicação de regex em bancos de dados.

Você pode estudar regex e aprender algumas de suas regras básicas, como as apresentadas no curso, e à medida que você se familiariza com o uso de regex, pode começar a explorar outras funcionalidades e recursos mais avançados para criar padrões mais complexos em seus códigos.

03.Desafio: trabalhando em outros contextos
---

**Etapa 3**

* **Projeto desafio 1**: vendas online

Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

Sabendo disso, manipule os textos presentes na coluna `Cliente` para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [62]:
# transformando as letras dos clientes em minuscula
dados1['Cliente'] = dados1['Cliente'].str.lower()
# removendo simbolos e digitos numéricos da coluna
dados1['Cliente'] = dados1['Cliente'].str.replace('[^a-z ]','',regex=True).str.strip()
dados1

   Data de venda         Cliente  Valor da compra
0     06/06/2022       ana lucia           836.50
1     06/06/2022  diego armandiu           573.33
2     06/06/2022  diego armandiu           392.80
3     06/06/2022  diego armandiu           512.34
4     07/06/2022  isabely joanes           825.31
5     07/06/2022  isabely joanes           168.07
6     07/06/2022  isabely joanes           339.18
7     07/06/2022  isabely joanes           314.69
8     08/06/2022  isabely joanes           682.05
9     08/06/2022     joo gabriel           386.34
10    08/06/2022  julya meireles           622.65
11    08/06/2022  julya meireles           630.79
12    09/06/2022  julya meireles           390.30
13    09/06/2022     maria julia           759.16
14    09/06/2022     maria julia           334.47
15    09/06/2022     maria julia           678.78
16    10/06/2022     maria julia           314.24
17    10/06/2022     pedro pasco           311.15
18    10/06/2022    paulo castro           899.16
19    10/06/2022   thiago fritzz           885.24

* **Projeto desafio 2: administração de condomínios**

**Na etapa 2**, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto `(blocoAP)`. Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna `apartamento` para remover o texto `(blocoAP)` do DataFrame.

In [63]:
# removendo o texto (blocoAP) da coluna apartamento do df 'dados2'
dados2['apartamento'] = dados2['apartamento'].str.replace(' \(blocoAP\)','',regex=True)
dados2

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 01/06/2022         05/06/2022         1000.0
1         A101                 01/07/2022         03/07/2022         2500.0
2         A102                 02/06/2022         02/06/2022         1100.0
3         A102                 02/07/2022         06/07/2022         2600.0
4         B201                 03/06/2022         07/06/2022         1200.0
5         B201                 03/07/2022         03/07/2022         2700.0
6         B202                 04/06/2022         07/06/2022         1300.0
7         B202                 04/07/2022         05/07/2022         2800.0
8         C301                 05/06/2022         10/06/2022         1400.0
9         C301                 05/07/2022         09/07/2022         2900.0
10        C302                 06/06/2022         08/06/2022         1500.0
11        C302                 06/07/2022         12/07/2022         1200.0
12        D401                 07/06/2022         07/06/2022         1600.0
13        D401                 07/07/2022         09/07/2022         1300.0
14        D402                 08/06/2022         10/06/2022         1700.0
15        D402                 08/07/2022         14/07/2022         1400.0
16        E501                 09/06/2022         10/06/2022         1800.0
17        E501                 09/07/2022         09/07/2022         1500.0
18        E502                 10/06/2022         16/06/2022         1900.0
19        E502                 10/07/2022         12/07/2022         1600.0
20        F601                 11/06/2022         17/06/2022         2000.0
21        F601                 11/07/2022         13/07/2022         1000.0
22        F602                 12/06/2022         15/06/2022         2100.0
23        F602                 12/07/2022         12/07/2022         1100.0
24        G701                 13/06/2022         19/06/2022         2200.0
25        G701                 13/07/2022         20/07/2022         1200.0
26        G702                 14/06/2022         15/06/2022         2300.0
27        G702                 14/07/2022         17/07/2022         2100.0
28        H801                 15/06/2022         18/06/2022         2400.0
29        H801                 15/07/2022         16/07/2022         2200.0

04.Para saber mais: o tipo datetime
---

A classe `datetime` é um tipo de dado que representa uma data e hora específicas em Python. Ela permite trabalhar e manipular dados de ano, mês, dia, hora, minuto, segundo e microssegundo, além de dias da semana, como segunda, terça, quarta, etc. Essa classe é definida no módulo `datetime` e é fundamental na manipulação de datas e horários em Python. Com ela, é possível realizar operações de cálculo de diferenças entre datas, formatação de datas e horas em diferentes formatos, além de ser muito útil em análises de dados que envolvem séries temporais.

Com a biblioteca Pandas, é possível realizar diversas operações com datas e horários, como a conversão de dados de string para `datetime`, a filtragem de dados baseada em intervalos de tempo específicos, a agregação de dados por hora, dia, mês ou ano, entre outras funcionalidades. Desse modo, com essa biblioteca, é possível realizar diversas operações com datas de forma simples e eficiente dentro de um conjunto de dados.

**Biblioteca datetime**

Conseguimos trabalhar diretamente com o `datetime` através da biblioteca datetime, uma biblioteca padrão do Python que fornece classes para trabalhar com datas e horas. Com essa biblioteca, é possível criar objetos de data e hora, realizar cálculos de tempo, formatar datas e horas em diferentes formatos e muito mais.

Dentro da biblioteca datetime, existe a classe datetime, que representa uma data e hora específicas. Veja um exemplo:

```
import datetime

# criando um objeto datetime com a data e hora atual
agora = datetime.datetime.now()

print("Data e hora atual:", agora)
```
Neste exemplo, o método `now()` da classe datetime é usado para criar um objeto que representa a data e a hora atual. O objeto resultante é armazenado na variável `agora` e, em seguida, é impresso na tela usando a função `print()`.

Outra classe importante na biblioteca datetime é a classe date, que representa apenas uma data. Veja um exemplo:

```
import datetime
# criando um objeto date com a data de hoje
hoje = datetime.date.today()

print("Data de hoje:", hoje)
```

Neste exemplo, o método `today()` da classe date é usado para criar um objeto que representa a data de hoje. O objeto resultante é armazenado na variável hoje e, em seguida, é impresso na tela usando a função `print()`.

A biblioteca datetime também permite realizar operações matemáticas com datas e horas. Veja um exemplo de como calcular a diferença entre duas datas:

```
import datetime

# criando dois objetos date com datas diferentes
data_1 = datetime.date(2022, 1, 1)
data_2 = datetime.date(2023, 1, 1)

# calculando a diferença entre as duas datas
diferenca = data_2 - data_1

print("Diferença entre as duas datas:", diferenca)
```

Neste exemplo, dois objetos date são criados com datas diferentes. Em seguida, o operador de subtração é usado para calcular a diferença entre as duas datas. O resultado é armazenado na variável `diferenca` e, em seguida, é impresso na tela usando a função `print()`.


Para se aprofundar nos usos do tipo datetime consulte o artigo [Python datetime: Como faço para definir data e hora em Python?](https://www.alura.com.br/artigos/lidando-com-datas-e-horarios-no-python) e também a documentação da [biblioteca datetime](https://docs.python.org/3/library/datetime.html).

04.Desafio: trabalhando em outros contextos
---

**Etapa 4**
* **Projeto desafio 1: vendas online**

Nas etapas anteriores, já trabalhamos com vários tipos de dados, agora podemos trabalhar com os dados de tempo.

Na coluna `Data de venda`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 1, vou deixar abaixo o texto da situação para facilitar o encontro da informação:


> O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

In [77]:
dados1

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

In [84]:
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados1['Data de venda'] = pd.to_datetime(dados1['Data de venda'], format='%d/%m/%Y')
# Visualizar o resultado
dados1

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

In [86]:
# Verificar o resultado da transformação
dados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [97]:
# Calcular o total arrecadado em compras por cada cliente do maior para o menor
total_compras1 = dados1.groupby(['Cliente'])['Valor da compra'].sum().sort_values(ascending=False)
# Visualizar o resultado
total_compras1

Cliente
isabely joanes    2329.30
maria julia       2086.65
julya meireles    1643.74
diego armandiu    1478.47
paulo castro       899.16
thiago fritzz      885.24
ana lucia          836.50
joo gabriel        386.34
pedro pasco        311.15
Name: Valor da compra, dtype: float64

* **Projeto desafio 2: administração de condomínios**

Assim como no projeto desafio 1, trabalhamos com todas as colunas exceto as que envolvem datas.

Nas colunas `datas_de_pagamento` e `datas_combinadas_pagamento`, temos datas em formato 'dia/mês/ano' (`dd/mm/AAAA`). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 2, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

> A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

In [121]:
# verificação do df
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4 days
1,A101,2022-07-01,2022-07-03,2500.0,2 days
2,A102,2022-06-02,2022-06-02,1100.0,0 days
3,A102,2022-07-02,2022-07-06,2600.0,4 days
4,B201,2022-06-03,2022-06-07,1200.0,4 days
5,B201,2022-07-03,2022-07-03,2700.0,0 days
6,B202,2022-06-04,2022-06-07,1300.0,3 days
7,B202,2022-07-04,2022-07-05,2800.0,1 days
8,C301,2022-06-05,2022-06-10,1400.0,5 days
9,C301,2022-07-05,2022-07-09,2900.0,4 days
10,C302,2022-06-06,2022-06-08,1500.0,2 days
11,C302,2022-07-06,2022-07-12,1200.0,6 days
12,D401,2022-06-07,2022-06-07,1600.0,0 days
13,D401,2022-07-07,2022-07-09,1300.0,2 days
14,D402,2022-06-08,2022-06-10,1700.0,2 days
15,D402,2022-07-08,2022-07-14,1400.0,6 days
16,E501,2022-06-09,2022-06-10,1800.0,1 days
17,E501,2022-07-09,2022-07-09,1500.0,0 days
18,E502,2022-06-10,2022-06-16,1900.0,6 days
19,E502,2022-07-10,2022-07-12,1600.0,2 days
20,F601,2022-06-11,2022-06-17,2000.0,6 days
21,F601,2022-07-11,2022-07-13,1000.0,2 days
22,F602,2022-06-12,2022-06-15,2100.0,3 days
23,F602,2022-07-12,2022-07-12,1100.0,0 days
24,G701,2022-06-13,2022-06-19,2200.0,6 days
25,G701,2022-07-13,2022-07-20,1200.0,7 days
26,G702,2022-06-14,2022-06-15,2300.0,1 days
27,G702,2022-07-14,2022-07-17,2100.0,3 days
28,H801,2022-06-15,2022-06-18,2400.0,3 days
29,H801,2022-07-15,2022-07-16,2200.0,1 days

In [122]:
# Transformar para o tipo datetime definindo o formato de data como DD/MM/AAAA ('%d/%m/%Y')
dados2['datas_combinadas_pagamento'] = pd.to_datetime(dados2['datas_combinadas_pagamento'], format="%d/%m/%Y")
dados2['datas_de_pagamento'] = pd.to_datetime(dados2['datas_de_pagamento'], format="%d/%m/%Y")

# Visualizar o resultado
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4 days
1,A101,2022-07-01,2022-07-03,2500.0,2 days
2,A102,2022-06-02,2022-06-02,1100.0,0 days
3,A102,2022-07-02,2022-07-06,2600.0,4 days
4,B201,2022-06-03,2022-06-07,1200.0,4 days
5,B201,2022-07-03,2022-07-03,2700.0,0 days
6,B202,2022-06-04,2022-06-07,1300.0,3 days
7,B202,2022-07-04,2022-07-05,2800.0,1 days
8,C301,2022-06-05,2022-06-10,1400.0,5 days
9,C301,2022-07-05,2022-07-09,2900.0,4 days
10,C302,2022-06-06,2022-06-08,1500.0,2 days
11,C302,2022-07-06,2022-07-12,1200.0,6 days
12,D401,2022-06-07,2022-06-07,1600.0,0 days
13,D401,2022-07-07,2022-07-09,1300.0,2 days
14,D402,2022-06-08,2022-06-10,1700.0,2 days
15,D402,2022-07-08,2022-07-14,1400.0,6 days
16,E501,2022-06-09,2022-06-10,1800.0,1 days
17,E501,2022-07-09,2022-07-09,1500.0,0 days
18,E502,2022-06-10,2022-06-16,1900.0,6 days
19,E502,2022-07-10,2022-07-12,1600.0,2 days
20,F601,2022-06-11,2022-06-17,2000.0,6 days
21,F601,2022-07-11,2022-07-13,1000.0,2 days
22,F602,2022-06-12,2022-06-15,2100.0,3 days
23,F602,2022-07-12,2022-07-12,1100.0,0 days
24,G701,2022-06-13,2022-06-19,2200.0,6 days
25,G701,2022-07-13,2022-07-20,1200.0,7 days
26,G702,2022-06-14,2022-06-15,2300.0,1 days
27,G702,2022-07-14,2022-07-17,2100.0,3 days
28,H801,2022-06-15,2022-06-18,2400.0,3 days
29,H801,2022-07-15,2022-07-16,2200.0,1 days

In [125]:
# Para contribuir na solução do contexto é possível calcular a diferença de dias
# entre a data combinada e a data de pagamento com dt.days
dados2['atraso'] = (dados2['datas_de_pagamento'] - dados2['datas_combinadas_pagamento']).dt.days
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4
5,B201,2022-07-03,2022-07-03,2700.0,0
6,B202,2022-06-04,2022-06-07,1300.0,3
7,B202,2022-07-04,2022-07-05,2800.0,1
8,C301,2022-06-05,2022-06-10,1400.0,5
9,C301,2022-07-05,2022-07-09,2900.0,4
10,C302,2022-06-06,2022-06-08,1500.0,2
11,C302,2022-07-06,2022-07-12,1200.0,6
12,D401,2022-06-07,2022-06-07,1600.0,0
13,D401,2022-07-07,2022-07-09,1300.0,2
14,D402,2022-06-08,2022-06-10,1700.0,2
15,D402,2022-07-08,2022-07-14,1400.0,6
16,E501,2022-06-09,2022-06-10,1800.0,1
17,E501,2022-07-09,2022-07-09,1500.0,0
18,E502,2022-06-10,2022-06-16,1900.0,6
19,E502,2022-07-10,2022-07-12,1600.0,2
20,F601,2022-06-11,2022-06-17,2000.0,6
21,F601,2022-07-11,2022-07-13,1000.0,2
22,F602,2022-06-12,2022-06-15,2100.0,3
23,F602,2022-07-12,2022-07-12,1100.0,0
24,G701,2022-06-13,2022-06-19,2200.0,6
25,G701,2022-07-13,2022-07-20,1200.0,7
26,G702,2022-06-14,2022-06-15,2300.0,1
27,G702,2022-07-14,2022-07-17,2100.0,3
28,H801,2022-06-15,2022-06-18,2400.0,3
29,H801,2022-07-15,2022-07-16,2200.0,1

In [120]:
# Calcular a média de tempo de atraso por apartamentos
media_atraso_dados2 = dados2.groupby(['apartamento'])['atraso'].mean()
# Visualizar o resultado
media_atraso_dados2

apartamento
A101   3 days 00:00:00
A102   2 days 00:00:00
B201   2 days 00:00:00
B202   2 days 00:00:00
C301   4 days 12:00:00
C302   4 days 00:00:00
D401   1 days 00:00:00
D402   4 days 00:00:00
E501   0 days 12:00:00
E502   4 days 00:00:00
F601   4 days 00:00:00
F602   1 days 12:00:00
G701   6 days 12:00:00
G702   2 days 00:00:00
H801   2 days 00:00:00
Name: atraso, dtype: timedelta64[ns]

Referências
---

1. [IO Tools (Text, CSV, HDF5, ...) (gratuito, inglês, texto)](https://pandas.pydata.org/docs/user_guide/io.html)
> Este é um guia de usuário do Pandas que aborda as ferramentas IO, incluindo como trabalhar com formatos de arquivo Text, CSV, HDF5, etc. Abrange tudo, desde leitura e escrita até formatos de dados binários e strings de texto, bem como seleção e indexação de dados.

2.  [Working with Text Data (gratuito, inglês, texto)](https://pandas.pydata.org/docs/user_guide/text.html)
> Parte do guia do usuário do Pandas, este recurso fornece uma ampla variedade de informações sobre como trabalhar com dados de texto. Ele cobre tópicos como métodos de string, substituição de string, indexação de string e muito mais.

3. [Regex101 (gratuito, inglês, código)](https://regex101.com/)
> Regex101 é um recurso online que permite aos usuários escrever, testar e depurar expressões regulares. Disponível gratuitamente, oferece uma interface de usuário intuitiva e recursos como uma biblioteca de expressões regulares e uma seção de explicação.

4. [re - Regular expression operations (gratuito, inglês, texto)](https://docs.python.org/3/library/re.html)
>Este é um material do site oficial do Python que trata de operações de expressão regular. Ele fornece uma descrição detalhada da biblioteca 're' em Python, explicando como usar expressões regulares para pesquisas e operações de substituição.

5. [datetime - Operações básicas de data e hora (gratuito, português, texto)](https://docs.python.org/pt-br/3/library/datetime.html)
>Este é um documento oficial da biblioteca Python abordando a biblioteca datetime. Ele explica como usar a biblioteca para realizar operações básicas de data e hora em Python, incluindo manipulação de data, hora e datetime.

6. [Time series / date functionality (gratuito, inglês, texto)](https://pandas.pydata.org/docs/user_guide/timeseries.html)
>Parte do guia do usuário do Pandas, este texto fornece uma visão detalhada da funcionalidade de série temporal e data. Ele explica como o Pandas facilita a manipulação e análise de dados de série temporal, incluindo frequências, resampling, etc.